### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by RandomModderJDK** [aimok04/iserv_exercise_discord_webhook#1]
I really like your creation. But it suddenly stopped working.
The error when executed in console:
```
(node:15048) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at Node.<anonymous> (\iserv_exercise_discord_webhook\IServClient.js:83:25)
    at initialize.each (\iserv_exercise_discord_webhook\node_modules\cheerio\lib\api\traversing.js:553:26)
    at Node.<anonymous> (\iserv_exercise_discord_webhook\IServClient.js:79:40)
    at initialize.each (\iserv_exercise_discord_webhook\node_modules\cheerio\lib\api\traversing.js:553:26)
    at \nodejs\iserv_exercise_discord_webhook\IServClient.js:74:59
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15048) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15048) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aimok04** [comment]
Hi,
Seems like they changed up the exercises ui a little bit. This should be fixed with the latest commit. Thanks for letting me know! :)
